version: '3.8'

services:
  jekyll:
    build:
      context: .  # 현재 디렉토리를 빌드 컨텍스트로 사용
      dockerfile: dockerfile  # 사용할 Dockerfile 이름 (Dockerfile이 현재 디렉토리에 있어야 함)
    ports:
      - "4000:4000"  # 호스트의 4000번 포트를 컨테이너의 4000번 포트에 매핑
    volumes:
      - .:/app # 현재 디렉토리를 컨테이너의 /app
